name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildlinux:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v2
      - name: 🔌 Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: ⏳ Install
        run: npm ci
      - name: 🚀 Build
        run: npm run build
